// Reads content/posts/*.md and emits a typed module the app imports directly.
// Compiling at build time (rather than fetching at runtime) is what lets the
// post pages prerender with their real body text in the HTML.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const postsDir = join(root, 'content', 'posts');
const outFile = join(root, 'src', 'app', 'core', 'content.generated.ts');

// Minimal frontmatter: `key: value` lines between --- fences. No nesting.
function parse(raw) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(raw);
  if (!match) return { meta: {}, body: raw };

  const meta = {};
  for (const line of match[1].split(/\r?\n/)) {
    const at = line.indexOf(':');
    if (at === -1) continue;
    const key = line.slice(0, at).trim();
    let value = line.slice(at + 1).trim().replace(/^["']|["']$/g, '');
    meta[key] = key === 'tags'
      ? value.split(',').map((t) => t.trim()).filter(Boolean)
      : value;
  }
  return { meta, body: match[2] };
}

const files = readdirSync(postsDir).filter((f) => f.endsWith('.md'));

const posts = files.map((file) => {
  const { meta, body } = parse(readFileSync(join(postsDir, file), 'utf8'));
  const slug = meta.slug || file.replace(/\.md$/, '');
  const words = body.split(/\s+/).filter(Boolean).length;

  if (!meta.title) throw new Error(`${file}: missing "title" in frontmatter`);
  if (!meta.date) throw new Error(`${file}: missing "date" in frontmatter`);

  return {
    slug,
    title: meta.title,
    date: meta.date,
    summary: meta.summary || '',
    tags: meta.tags || [],
    draft: meta.draft === 'true',
    readingMinutes: Math.max(1, Math.round(words / 220)),
    html: marked.parse(body, { async: false }),
  };
});

// Newest first; drafts never reach the build.
const published = posts
  .filter((p) => !p.draft)
  .sort((a, b) => (a.date < b.date ? 1 : -1));

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `// GENERATED by scripts/build-content.mjs — do not edit.\n` +
    `// Source: content/posts/*.md\n\n` +
    `export interface Post {\n` +
    `  slug: string;\n  title: string;\n  date: string;\n  summary: string;\n` +
    `  tags: string[];\n  readingMinutes: number;\n  html: string;\n}\n\n` +
    `export const posts: Post[] = ${JSON.stringify(published, (k, v) => (k === 'draft' ? undefined : v), 2)};\n`,
  'utf8',
);

// Sitemap and robots ship as static assets so the crawler sees every prerendered route.
const origin = 'https://brandonscottlang.com';
const routes = ['', 'writing', 'builds', 'lab', 'about', ...published.map((p) => `writing/${p.slug}`)];
const today = new Date().toISOString().slice(0, 10);

const urls = routes
  .map((r) => `  <url><loc>${origin}/${r}</loc><lastmod>${today}</lastmod></url>`)
  .join('\n');

writeFileSync(
  join(root, 'public', 'sitemap.xml'),
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    urls +
    '\n</urlset>\n',
  'utf8',
);

writeFileSync(
  join(root, 'public', 'robots.txt'),
  `User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`,
  'utf8',
);

console.log(`content: ${published.length} post(s), ${routes.length} sitemap url(s)`);
